name: ci_meson

on:
  push:
  pull_request:

jobs:
  linux:
    # ubuntu-lastest ships a version of meson that is too old
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc meson libomp-dev bats
      - name: Setup
        run: cd src/c/ && meson build

      - name: Build & Test
        run: |
          cd src/c && BIN="$(pwd)/build/cgol" test/test.bats


